### ISSUE TITLE
Morning Session Code Review | Missing LInks In Social Contacts

### ISSUE THREAD

**Issue by harlexkhal** [mnekx/my-portfolio#6]
It was really hard for me finding issues with your project at the moment because it was almost perfect but just a suggestion Including actual links to your social media would help a lot in people reaching out to you when they need to.

**Comment by zmekonnen251** [comment]
I see you put the navbar outside of the header HTML semantic element. I think the navbar should be in the header.

**Comment by vikipretium** [comment]
### Hi @mnekx  ,
You did a really good job so far, on this project!
There are some issues that you still need to work on this project!
To highlight:

✔Descriptive pull request.
✔Descriptive commit messages.
✔Used both flexbox and grid as per requirement.
✔Design matches the template.
Required Changes ♻️
Please check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

**Comment by mnekx** [comment]
Thanks guys for awesome inputs. I have worked on these issues and I am closing now. 
Again, Thanks. 🤝
